theme: jekyll-theme-cayman
title: Internal Platforms
tagline: Resources about Internal Platform teams and products
description: >-
  Resources about Internal Platforms teams and products
tags:
  - Internal Platform teams
url: "https://internalplatforms.com"
plugins:
  - jekyll-sitemap
